line-length = 120

[lint]
# https://docs.astral.sh/ruff/settings/#select
# default for select is ["E4", "E7", "E9", "F"]
# we add D for docstrings, and N for naming conventions
extend-select = ["D", "N"]
ignore = ["E501", "D100", "D101", "D102", "D103", "D104", "D105", "E731", "D407"]

[lint.pydocstyle]
convention = "numpy"
